name: virtuan-studio-ui

on:
  push:
    branches: [ vd-dev3 ]
  pull_request:
    branches: [ vd-dev3 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install
    - run: npm install -g @angular/cli
    - run: npm run build:prod
    - name: build and deploy
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: virtuan/dev
          tags: virtuan-studio-editor-dev-$GITHUB_RUN_ID
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
