name: virtuan-studio-ui

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install
    - run: npm install -g @angular/cli
    - run: npm run build:prod
    - name: build and deploy
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: virtuan/prod
          tags: virtuan-studio-editor-latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
